### ISSUE TITLE
Question about the out.txt

### ISSUE THREAD

**Issue by bobykhani** [diogomg/MobFogSim#1]
Hi Diogo
I have a question about some parameters in "out.txt" which generate by running the simulation. At the end of the file where migration details are shown, there is a "Total of migrations" and a "Total of migration to differents SC". What's different between these two and why the results of them are different? I debug the code and some times at the end of the migration process VM delivered but sometimes not and It really confused me. I think it's due to postcopystatus but I don't understand how. can you help me?

**Comment by diogomg** [comment]
Hi bobyshani,

'Total of migration to different SC' is a bad description of what that metric means. I will push a commit to fix it.

Each access point and cloudlet has a coverage area (defined in vmmobile.constants.MaxAndMin). The connection between APs and cloudlets are based on that coverage. When a user finishes a handoff, he is for sure under a different AP coverage area and may be in a different cloudlet area. That metric counts how many times the user falls outside the cloudlet's area which he is currently connected to.

About your second question, I am not sure if I completely understood. One migration will not be finished only if the user ends his travel during the migration process.

I would be thankful if you may provide me the settings you are using.
